name: First Workflow

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1
        run: echo "Step 1 complete!"

      - name: Step 2
        run: echo "Step 2 complete!"

  job2:
    runs-on: ubuntu-latest

    steps:
      - name: Cowsays
        # The 'uses' command executes a remote GitHub action.
        # A command like mscoutermarsh/cowsays-action means you can
        # find this code at https://github.com/mscoutermarsh/cowsays-action
        uses: mscoutermarsh/cowsays-action@master
        # The 'with' block includes parameters that the workflow will pass
        # to this action. Parameters are all in key-value format.
        with:
          text: 'Ready for prod--ship it!'
          color: 'magenta'
